replicaCount: 1
image:
  repository: $repository
  tag: "$tag"
  pullPolicy: Always
  secrets: []
extraLabels:
  "ID": "$service_id"
gitlab:
  app: "$app_name"
  envURL: "$repo_url"
service:
  enabled: true
  name: "web"
  url: "$public_url"
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000
ingress:
  enabled: true
  path: "/"
  annotations:
    kubernetes.io/ingressClassName: "nginx"
livenessProbe:
  path: /health
  initialDelaySeconds: 15
  timeoutSeconds: 15
  periodSeconds: 30
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: /health
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
  probeType: "httpGet"
