services:
  minio:
    image: minio/minio:latest
    container_name: dariah-knowledge-base-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":${MINIO_WEB_UI_PORT:-9001}"
    ports:
      - "${S3_PORT:-9000}:9000"
      - "${MINIO_WEB_UI_PORT:-9001}:9001"
    volumes:
      - minio-data:/data

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    container_name: dariah-knowledge-base-imgproxy
    restart: unless-stopped
    depends_on:
      - minio
    environment:
      # IMGPROXY_MALLOC: jemalloc
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      IMGPROXY_USE_S3: true
      IMGPROXY_ALLOWED_SOURCES: s3://
      IMGPROXY_S3_ENDPOINT: http://minio:${S3_PORT:-9000}
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}
      AWS_EC2_METADATA_DISABLED: true
    ports:
      - "${IMGPROXY_PORT:-8080}:8080"

volumes:
  minio-data:
