services:
  app:
    image: ghcr.io/acdh-oeaw/devcontainer-frontend:24
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:postgres
    depends_on:
      - postgres
