services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
    ports:
      - "${MAILPIT_WEB_UI_PORT}:8025"
      - "${EMAIL_SMTP_PORT}:1025"
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_ENABLE_CHAOS: true

volumes:
  mailpit-data:
