name: Validate

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-validate"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: true
      matrix:
        node-version: [24.x]
        os: [ubuntu-24.04]

    env:
      DATABASE_HOST: "localhost"
      DATABASE_NAME: "dariah-knowledge-base"
      DATABASE_PASSWORD: "dariah-knowledge-base"
      DATABASE_PORT: "5432"
      DATABASE_USER: "dariah-knowledge-base"
      EMAIL_ADDRESS: "acdh@example.com"
      EMAIL_SMTP_PORT: "1025"
      EMAIL_SMTP_SERVER: "localhost"
      IMGPROXY_BASE_URL: "http://localhost:8080"
      IMGPROXY_KEY: "799b9a1ea1ee6b18339b9b3c03b7424ac9fd75d0e5777e5a6258f5a541609a45"
      IMGPROXY_PORT: "8080"
      IMGPROXY_SALT: "b803f8f06b44263bd41dfee1d0e5e958"
      MAILPIT_API_BASE_URL: "http://localhost:8025"
      NEXT_PUBLIC_APP_BASE_URL: "http://localhost:3000"
      NEXT_PUBLIC_IMPRINT_SERVICE_BASE_URL: "${{ vars.NEXT_PUBLIC_IMPRINT_SERVICE_BASE_URL }}"
      NEXT_PUBLIC_MATOMO_BASE_URL: "${{ vars.NEXT_PUBLIC_MATOMO_BASE_URL }}"
      NEXT_PUBLIC_MATOMO_ID: "${{ vars.NEXT_PUBLIC_MATOMO_ID }}"
      NEXT_PUBLIC_REDMINE_ID: "${{ vars.SERVICE_ID }}"
      NEXT_PUBLIC_TYPESENSE_COLLECTION_NAME: "dariah-knowledge-base"
      NEXT_PUBLIC_TYPESENSE_HOST: "localhost"
      NEXT_PUBLIC_TYPESENSE_PORT: "8108"
      NEXT_PUBLIC_TYPESENSE_PROTOCOL: "http"
      S3_ACCESS_KEY: "c8c7bab1e784e088780bdc97876cfdc0"
      S3_BUCKET: "dariah-knowledge-base"
      S3_HOST: "localhost"
      S3_PORT: "9000"
      S3_PROTOCOL: "http"
      S3_SECRET_KEY: "f98c5ba01f5e5781f0eb09d7b74b36bc8c10cc67b010cead4fcbe8c1605ccf33"
      TYPESENSE_ADMIN_API_KEY: "050b1c25823ea77fe35fa8814373a000b031e27d27fb38b3d2b573cc1516f8da"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install turborepo cli globally
        run: pnpm add --global turbo

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: turbo run format:check

      - name: Lint
        run: turbo run lint:check

      - name: Typecheck
        run: turbo run types:check

      - name: Test
        run: turbo run test

      - name: Get playwright version
        run: |
          PLAYWRIGHT_VERSION=$(pnpm ls @playwright/test --json | jq --raw-output '.[0].devDependencies["@playwright/test"].version')
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache playwright browsers
        uses: actions/cache@v4
        id: cache-playwright-browsers
        with:
          path: "~/.cache/ms-playwright"
          key:
            "${{ matrix.os }}-${{ matrix.node-version }}-playwright-browsers-${{
            env.PLAYWRIGHT_VERSION }}"

      - name: Install playwright browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps
      - name: Install playwright browsers (operating system dependencies)
        if: steps.cache-playwright-browsers.outputs.cache-hit == 'true'
        run: pnpm exec playwright install-deps

      # https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions
      - name: Cache next.js build output
        uses: actions/cache@v4
        with:
          path: "${{ github.workspace }}/.next/cache"
          key:
            "${{ matrix.os }}-${{ matrix.node-version }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}"

      - name: Build app
        run: turbo run build

      - name: Run e2e tests
        run: turbo run test:e2e

      - uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
